name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install stgit
        shell: bash
        run: |
          sudo apt-get install -y stgit
          git config --global user.name "Dmitry Khodorov"
          git config --global user.email "el1191@woyd.ru"
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Build
        shell: bash
        run: task prepare patch build push
